baseURL = 'http://nepaliproject.com'
languageCode = 'en-us'
title = 'A Nepali Project ;)'

# Novela settings
theme = "hugo-theme-novela-master"
paginate = 6

[social]
twitter = "#"
github= "#"
linkedin= "#" 
instagram = "#"
dribbble = "#"
youtube = "#"

[taxonomies]
author = "authors"

